language: python
python:
  - "2.7"
install:
  - pip install tox
script:
  - tox
notifications:
  irc: "chat.freenode.net#bug-assassins"
  on_success: always
  on_failure: always
after_success:
  - coveralls
