application: hrd-ajith1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: shard_app/static/
  secure: optional

- url: /cron/.*
  script: hrd_sharded_counters.wsgi.application
  login: admin
  secure: optional

- url: .*
  script: hrd_sharded_counters.wsgi.application
  secure: optional

libraries:
- name: django
  version: 1.5

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(\.tox/.*)
- ^(\.git/.*)
- pylintrc
- tox.ini
- LICENSE
- README.md
- ^(.*/)?.*\.csv$
- ^shard_app/.*\.pdf$
- ^shard_app/load_test/.*$
